### ISSUE TITLE
Build error for XCM

### ISSUE THREAD

**Issue by alakmazaheri** [ADVRHumanoids/advr-superbuild#17]
After following the Wiki installation, "make" breaks at building XCM for XBotCore (it successfully makes XBotInterface and RobotInterfaceROS before this):

```
[ 91%] Performing build step for 'XBotCore'
...
[ 28%] Built target XCM
Linking CXX executable bin/CommunicationHandler
devel/lib/libXCM.so.1.0.0: undefined reference to `robot_state_publisher::RobotStatePublisher::RobotStatePublisher(KDL::Tree const&, urdf::Model const&)'
devel/lib/libXCM.so.1.0.0: undefined reference to `vtable for robot_state_publisher::RobotStatePublisher'
collect2: error: ld returned 1 exit status
make[5]: *** [bin/CommunicationHandler-1.0.0] Error 1
make[4]: *** [CMakeFiles/CommunicationHandler.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [external/XBotCore/CMakeFiles/YCMStamp/XBotCore-build] Error 2
make[1]: *** [CMakeFiles/XBotCore.dir/all] Error 2
make: *** [all] Error 2

```

I also tried using the devel branch since it embeds XCM into XBotCore, but got the same error.

**Comment by pepperig** [comment]
I guess you are using some old version. I suggest you to clone a  fresh superbuild.
The build is working as shown by the Travis CI at https://travis-ci.org/ADVRHumanoids/advr-superbuild

**Comment by alakmazaheri** [comment]
Unfortunately, this error came from a superbuild that I cloned earlier today. I just tried making a new one with the same git clone statement as used by Travis CI, but got stuck in the same place.

**Comment by liesrock** [comment]
Hi @alakmazaheri, thanks for the interest! I believe this kind of issues are related to the failure of the get dependency script while installing one of the system packet required by XBotCore. You probably have unmet dependencies. Travis starts from a clean o.s. in fact and is now passing.

**Comment by pepperig** [comment]
I think you are using some branch different from the master.

**Comment by liesrock** [comment]
Anyhow we are planning to release a .deb package of the framework: I will update you ASAP about this.

**Comment by alakmazaheri** [comment]
Thank you very much! I am going to try the process again on a new computer with a clean OS. I look forward to seeing the .deb package version. This is an awesome project!

**Comment by liesrock** [comment]
@alakmazaheri you can find the .deb here: https://github.com/ADVRHumanoids/XBotControl
