### ISSUE TITLE
RBDL version is not set from Buildrbdl.cmake

### ISSUE THREAD

**Issue by liesrock** [ADVRHumanoids/advr-superbuild#31]
RBDL is held in mercurial (hg) and I tried to set a specific version using the Builrbdl.cmake : 

```
# rbdl 
include(YCMEPHelper)
include(FindOrBuildPackage)

ycm_ep_helper(  rbdl
                TYPE HG
                STYLE BITBUCKET
                REPOSITORY rbdl/rbdl
                TAG 338e4db
		CMAKE_CACHE_ARGS -DRBDL_BUILD_ADDON_URDFREADER:BOOL=ON
                COMPONENT external
            )
```

Nevertheless the superbuild is not taking the requested TAG as reported by @dkanou.

Any idea? @alaurenzi @traversaro

**Comment by traversaro** [comment]
Have you tried with the complete  commit hash or with a tag?

**Comment by traversaro** [comment]
In https://github.com/traversaro/gazebo-superbuild  I successfully use `ycm_ep_helper` with mercurial, but I always use branches names as tag.

**Comment by liesrock** [comment]
Here you can find the error: https://travis-ci.com/ADVRHumanoids/MultiDoF-superbuild/builds/107606808

Looks like the TAG is not working for hash: I confirm we used it successfully with branches
![rbdl_error](https://user-images.githubusercontent.com/1098646/55795275-ada87180-5ac7-11e9-9680-03e2b2a4fe84.png)

**Comment by traversaro** [comment]
Have you tried using `338e4dbb4fa2644af1598db9a4c95cd39b6b981a` instead of `338e4db`?

**Comment by liesrock** [comment]
I was not able to solve it unfortunately: maybe @drdanz knows how?

**Comment by drdanz** [comment]
No idea, perhaps it is a bug in `ExternalProject`?
YCMEPHelper is forwarding the tag argument in the exact same way as the git tag is forwarded:

https://github.com/robotology/ycm/blob/ae223b18347a641873ca40aff482d15526ab9cde/modules/YCMEPHelper.cmake#L998-L1000

**Comment by liesrock** [comment]
Thanks for the support: since it was very strange that the clone was always happening on 379184776089 I thought there would be some other files overwriting the requested TAG.

And it was like this: ProjectTags.cmake was overwriting (we had the 379184776089 commit on it for rbdl) everything I put on Buildrbdl.cmake

Fixed in https://github.com/ADVRHumanoids/advr-superbuild/commit/cc8c14303675733a97b67e1ec0a6d84fb1d0d2ba
