### ISSUE TITLE
door handling module restarting issue

### ISSUE THREAD

**Issue by JinohLee** [ADVRHumanoids/advr-superbuild#4]
We did the following in sequence
1. Started the door handling module and send the handle pose.
2. While the robot hand was moving to the handle, we stopped the module.
3. After our module stopped, we started the homing module and observed the robot moving safely to the homing pose.
4. We restarted the door handling module and send the handle pose.
The door handling module starts from the beginning as programmed, but once we hit the send handle pose, the robot starts executing the motion which we interrupted in Step 2. Maybe this is associated with the shared data, which needs to be flushed whenever we restart the module.

**Comment by pepperig** [comment]
Hi,
we need to give a look a the code. However consider that when you restart the plugin just the OnStart() method is called. The plugin's init() method does not get called. So if in your execution you rely on some initialization you have to modify the code accordingly.

**Comment by JinohLee** [comment]
We've checked the initialization code and confirmed the variables and messages in shared data are properly initialized. 
Indeed, we got impression that when we stop the module during the trajectory execution, shared data related to the robot position seem to be remained in a certain process out of our Plugin, for instance in openSOT. 
If it is true, then other plugins would have the same behavior.
Hope to see the code together.  Thanks.

**Comment by pepperig** [comment]
@liesrock

**Comment by pepperig** [comment]
@rsubburaman  pull the ManipulationPlugin, compile it and try! let me know!

**Comment by liesrock** [comment]
It should be solved right?

**Comment by rsubburaman** [comment]
The issue was solved after the update in the manipulation plugin.
